/**
 * @author J. Santos <jamillo@gmail.com>
 * @date July 20, 2016
 */

#include <gtest/gtest.h>
#include <json/value.h>
#include <config/videostream.h>

#define CONFIG_VIDEOSTREAM_CAMERA "/dev/video0"
#define CONFIG_VIDEOSTREAM_WIDTH 320
#define CONFIG_VIDEOSTREAM_HEIGHT 240
#define CONFIG_VIDEOSTREAM_SATURATION 1
#define CONFIG_VIDEOSTREAM_BRIGHTNESS 2
#define CONFIG_VIDEOSTREAM_CONTRAST 3
#define CONFIG_VIDEOSTREAM_HUE 4
#define CONFIG_VIDEOSTREAM_GAIN 5
#define CONFIG_VIDEOSTREAM_EXPOSURE 6

GTEST_TEST(config_videostream, constructor)
{
	mote::config::VideoStream config(CONFIG_VIDEOSTREAM_CAMERA, CONFIG_VIDEOSTREAM_WIDTH, CONFIG_VIDEOSTREAM_HEIGHT,
		CONFIG_VIDEOSTREAM_SATURATION, CONFIG_VIDEOSTREAM_BRIGHTNESS, CONFIG_VIDEOSTREAM_CONTRAST,
		CONFIG_VIDEOSTREAM_HUE, CONFIG_VIDEOSTREAM_GAIN, CONFIG_VIDEOSTREAM_EXPOSURE);
	ASSERT_EQ(CONFIG_VIDEOSTREAM_CAMERA, config.camera);
	ASSERT_EQ(CONFIG_VIDEOSTREAM_WIDTH, config.width);
	ASSERT_EQ(CONFIG_VIDEOSTREAM_HEIGHT, config.height);
	ASSERT_EQ(CONFIG_VIDEOSTREAM_SATURATION, config.saturation);
	ASSERT_EQ(CONFIG_VIDEOSTREAM_BRIGHTNESS, config.brightness);
	ASSERT_EQ(CONFIG_VIDEOSTREAM_CONTRAST, config.contrast);
	ASSERT_EQ(CONFIG_VIDEOSTREAM_HUE, config.hue);
	ASSERT_EQ(CONFIG_VIDEOSTREAM_GAIN, config.gain);
	ASSERT_EQ(CONFIG_VIDEOSTREAM_EXPOSURE, config.exposure);
}

GTEST_TEST(config_videostream, from_json)
{
	mote::config::VideoStream config;

	Json::Value json;
	json["camera"] = CONFIG_VIDEOSTREAM_CAMERA;
	json["width"] = CONFIG_VIDEOSTREAM_WIDTH;
	json["height"] = CONFIG_VIDEOSTREAM_HEIGHT;
	json["saturation"] = CONFIG_VIDEOSTREAM_SATURATION;
	json["brightness"] = CONFIG_VIDEOSTREAM_BRIGHTNESS;
	json["contrast"] = CONFIG_VIDEOSTREAM_CONTRAST;
	json["hue"] = CONFIG_VIDEOSTREAM_HUE;
	json["gain"] = CONFIG_VIDEOSTREAM_GAIN;
	json["exposure"] = CONFIG_VIDEOSTREAM_EXPOSURE;

	config.fromJson(json);
	ASSERT_EQ(CONFIG_VIDEOSTREAM_CAMERA, config.camera);
	ASSERT_EQ(CONFIG_VIDEOSTREAM_WIDTH, config.width);
	ASSERT_EQ(CONFIG_VIDEOSTREAM_HEIGHT, config.height);
	ASSERT_EQ(CONFIG_VIDEOSTREAM_SATURATION, config.saturation);
	ASSERT_EQ(CONFIG_VIDEOSTREAM_BRIGHTNESS, config.brightness);
	ASSERT_EQ(CONFIG_VIDEOSTREAM_CONTRAST, config.contrast);
	ASSERT_EQ(CONFIG_VIDEOSTREAM_HUE, config.hue);
	ASSERT_EQ(CONFIG_VIDEOSTREAM_GAIN, config.gain);
	ASSERT_EQ(CONFIG_VIDEOSTREAM_EXPOSURE, config.exposure);
}

GTEST_TEST(config_videostream, to_json)
{
	mote::config::VideoStream config(CONFIG_VIDEOSTREAM_CAMERA, CONFIG_VIDEOSTREAM_WIDTH, CONFIG_VIDEOSTREAM_HEIGHT,
		CONFIG_VIDEOSTREAM_SATURATION, CONFIG_VIDEOSTREAM_BRIGHTNESS, CONFIG_VIDEOSTREAM_CONTRAST,
		CONFIG_VIDEOSTREAM_HUE, CONFIG_VIDEOSTREAM_GAIN, CONFIG_VIDEOSTREAM_EXPOSURE);

	Json::Value json;
	config.toJson(json);
	ASSERT_EQ(CONFIG_VIDEOSTREAM_CAMERA, json["camera"].asString());
	ASSERT_EQ(CONFIG_VIDEOSTREAM_WIDTH, json["width"].asInt());
	ASSERT_EQ(CONFIG_VIDEOSTREAM_HEIGHT, json["height"].asInt());
	ASSERT_EQ(CONFIG_VIDEOSTREAM_SATURATION, json["saturation"].asInt());
	ASSERT_EQ(CONFIG_VIDEOSTREAM_BRIGHTNESS, json["brightness"].asInt());
	ASSERT_EQ(CONFIG_VIDEOSTREAM_CONTRAST, json["contrast"].asInt());
	ASSERT_EQ(CONFIG_VIDEOSTREAM_HUE, json["hue"].asInt());
	ASSERT_EQ(CONFIG_VIDEOSTREAM_GAIN, json["gain"].asInt());
	ASSERT_EQ(CONFIG_VIDEOSTREAM_EXPOSURE, json["exposure"].asInt());
}
